Ivan1996_1
Ivan1996$
Basic SXZhbjE5OTZfMTpJdmFuMTk5NiQ=
admin
Basic YWRtaW46YWRtaW4=
kate1998
Basic a2F0ZTE5OTg6dmVyeXNUUm9uZ1Bhc3N3b3JkMzMk


{
  "username": "Ivan1996_2",
  "password": "Ivan1996_)$",
  "role": "USER"
}

docker run -d -p 4111:4111 -name nbank nobugsme/nbank:with_validation_fix

docker run -d -p 4111:4111 --name nbank nobugsme/nbank:with_username_error_fix