version: '3.8'  # Версия формата Compose

services:
  # ==================== БАКЕНД СЕРВИС ====================
  backend:
    image: nobugsme/nbank:with_username_error_fix  # Используем готовый образ бекенда
    container_name: nbank-backend              # Явное имя контейнера для удобства
    ports:
      - "4111:4111"                           # Пробрасываем порт 4111 наружу
    networks:
      - nbank-network                         # Подключаем к общей сети
    restart: unless-stopped                   # Автоматически перезапускать при падении

  # ==================== ФРОНТЕНД СЕРВИС ====================
  frontend:
    image: nobugsme/nbank-ui:with_nginx
    container_name: nbank-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - nbank-network
    restart: unless-stopped

#  # ==================== NGINX ПРОКСИ ====================
#  nginx:
#    image: nginx:latest                       # Официальный образ Nginx
#    container_name: nbank-nginx
#    ports:
#      - "80:80"                               # Основной веб-порт
#      - "443:443"                             # HTTPS порт (можно настроить позже)
#    networks:
#      - nbank-network
#    restart: unless-stopped
#    depends_on:
#      - frontend
#      - backend
#    volumes:
#      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro    # Монтируем кастомную конфигурацию Nginx
#    # Nginx будет проксировать запросы к фронтенду и бекенду

  # ==================== SELENOID (SELENIUM) ====================
  selenoid:
    image: aerokube/selenoid:latest-release          # Основной образ Selenoid
    container_name: nbank-selenoid
    ports:
      - "4444:4444"
    networks:
      - nbank-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Доступ к Docker демону для запуска браузеров
      - ./config/:/etc/selenoid/:ro # Конфигурация Selenoid
    command: [ "-container-network", "nbank-network" ]
    depends_on:
      - frontend

  # ==================== SELENOID UI (ВЕБ-ИНТЕРФЕЙС) ====================
  selenoid-ui:
    image: aerokube/selenoid-ui:latest        # Веб-интерфейс для мониторинга Selenoid
    container_name: nbank-selenoid-ui
    ports:
      - "8080:8080"                           # Веб-интерфейс на порту 6567
    command: ["--selenoid-uri", "http://selenoid:4444"]
    networks:
      - nbank-network
    restart: unless-stopped
    depends_on:
      - selenoid                              # Зависит от основного Selenoid
# ==================== ОБЩАЯ СЕТЬ ====================
networks:
  nbank-network:
    name: nbank-network                     # Явное имя сети (опционально)
